<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Waybon.Application\Waybon.Application.csproj" />
    <ProjectReference Include="..\Waybon.Infrastructure\Waybon.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Waybon.Api</RootNamespace>
    <UserSecretsId>2b489b6a-98da-4ff4-83ae-72e8768d21a4</UserSecretsId>
  </PropertyGroup>

</Project>